name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: List files in /home/ec2-user/Demo
        run: ls -la /home/ec2-user/Demo
