name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and pull latest changes
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@98.81.177.145 << 'EOF'
          cd /home/ec2-user/Demo
          git pull origin main
        EOF
